### ISSUE TITLE
Ebuildtester does not get installed through snap

### ISSUE THREAD

**Issue by RafaelPalomar** [nicolasbock/ebuildtester#195] opened 2022-06-22 09:55 UTC
Trying to install ebuildtester through snap in Ubuntu 22.04 produces the following error:

```console
error: cannot perform the following tasks:
- Run configure hook of "ebuildtester" snap if present (run hook "configure": 
-----
Please run

snap connect ebuildtester:docker-executables docker:docker-executables

in order to use the ebuildtester command.
-----)
```
Issuing `snap connect ebuildtester:docker-executables docker:docker-executables` produces:
```
error: snap "ebuildtester" is not installed
```

**Comment by nicolasbock** [comment] 2022-06-22 11:43
Duplicate of nicolasbock/ebuildtester#193

**Comment by nicolasbock** [comment] 2022-06-22 11:43
Let me know if it works now.

**Closed by nicolasbock** 2022-06-22 11:43 UTC
Labels: duplicate

**Comment by RafaelPalomar** [comment] 2022-06-23 04:54
> Let me know if it works now.

That worked fine! Thank you very  much!
